### ISSUE TITLE
Cell Viability Prediction Error

### ISSUE THREAD

**Issue by BelindaBGarana** [bence-szalai/Cell-death-signatures#17]
Hi, I uploaded a gene expression matrix (.csv format) to predict cell viability using the CEVIChE tool. It appeared that the upload was successful, but once I pressed "Submit," I received an error message: "An error has occurred. Check your logs or contact the app author for clarification." I am attaching screenshots for reference, but my input matrix is too large (27 MB) to upload here.
Thanks in advance for your help!
<img width="1255" alt="Screen Shot 2022-10-26 at 4 34 44 PM" src="https://user-images.githubusercontent.com/75867404/198159099-56a513bf-2b50-44d6-87e5-419a35a32369.png">
<img width="812" alt="Screen Shot 2022-10-26 at 4 36 27 PM" src="https://user-images.githubusercontent.com/75867404/198159105-dbb40c3f-645a-4248-a58f-49451c0da424.png">

**Comment by bence-szalai** [comment]
Hi Belinda, thanks for contacting me regarding the problem. Without seeing the data it is hard to tell what is the problem. Could you please find some way to share the data with me (if it is possible) - via Google Drive or something similar? Thanks,

Bence

**Comment by BelindaBGarana** [comment]
Hi Bence, I replicated the same exact error with a smaller data file. I am attaching the smaller file of RNA expression data with which I also have the same issue. Thanks
[Transposed_Normalized_adherent_CCLE_RNAseq_19Q4_samples_in_PRISM_1-3.csv](https://github.com/bence-szalai/Cell-death-signatures/files/10059762/Transposed_Normalized_adherent_CCLE_RNAseq_19Q4_samples_in_PRISM_1-3.csv)

**Comment by christianholland** [comment]
Hi @BelindaBGarana,

thanks for reporting this issue. Unfortunately, you are facing this error due to a flaw in our app design. We expect that the gene column is named `gene`. In your example file it is named `Gene` (with a capital `G`). So changing it to `gene` should solve your issue.

Best,
Christian

**Comment by BelindaBGarana** [comment]
Hi Christian, I changed my gene name column to be named "gene" and it does run now. I just wanted to confirm that I am only supposed to receive one cell viability value per input sample? In other words, the CEVIChE web app does not predict sensitivity to the drugs in CTRPv2, but instead just one cell viability value for each input gene expression profile? Thank you

**Comment by bence-szalai** [comment]
Hi @BelindaBGarana , I am happy that it works now, thanks @christianholland . Regarding your question: yes, CEVIChE predicts one viability value for each gene expression profile. If you use perturbation gene expression profiles as input (gene expression after perturbation), than this predicted viability is the viability change induced by the given perturbation. If you use baseline, unperturbed gene expression profiles of cell lines (I think this is your case), then the predicted viability correlates with the division time of the given cell line. Hope it makes sense.

If you are interested for sensitivity to CTRP2 drugs, you should use gene expression profiles, where the cells were perturbed with CTRP2 drugs. 

Best,

Bence
